export const ticketData: ITicketData[] = [
  {
    ticketType: 1,
    color: "yellow",
    packageName: "General Access",
    dollar_price: "10",
    cedi_price: "100",
    perks: [
      "Party Bands",
      "Experience avenue",
      "Food Court access",
      "General Admission Access",
    ],
    available: true,
    countDown: false,
  },
  {
    ticketType: 2,
    color: "red",
    packageName: "General Access Plus",
    dollar_price: "20",
    cedi_price: "200",
    perks: [
      "Party Bands",
      "Access to Bar Area",
      "Merch area access",
      "Priority access to book buss",
      "Access to Cocktail Area",
      "Water",
      "Access to Experiential Center",
      "Access to food court",
    ],
    available: false,
    countDown: false,
  },
  {
    ticketType: 3,
    color: "green",
    packageName: "VIP",
    dollar_price: "40",
    cedi_price: "500",
    perks: [
      "Access to event bars",
      "Priority entry",
      "Autograph signing",
      "Merch access",
      "Meet and Great Sessions",
      "Access to our exclusive after party event",
      "Access to unlimited water and drinks cocktail",
      "An item of exclusive singing opportunity",
      "Unrestricted access to the front stage within arms reach with the artist",
    ],
    available: true,
    countDown: false,
  },
];
