export const ticketData: ITicketData[] = [
  {
    ticketType: 1,
    color: "yellow",
    packageName: "General Access",
    dollar_price: "10",
    cedi_price: "100",
    perks: [
      "Party Bands",
      "Experience avenue",
      "Food Court access",
      // "General Admission Access",
    ],
    available: true,
    countDown: false,
  },
  {
    ticketType: 2,
    color: "red",
    packageName: "General Access Plus",
    dollar_price: "20",
    cedi_price: "300",
    perks: [
      "Party Bands",
      "Merch area access",
      "After Party Access",
      "Experential Area Access",
      "Special Bar Access",
    ],
    available: true,
    countDown: false,
  },
  {
    ticketType: 3,
    color: "green",
    packageName: "VIP",
    dollar_price: "40",
    cedi_price: "500",
    perks: [
      "Access to VIP Bar",
      "Priority entry",
      "Access to priority car packing",
      "Unrestricted access to the front stage within arms reach with the artist",
      "Access to the zaama artist lounge",
      "Luxury serviced toilets",
      "VIP treat at the after party experience",
    ],
    available: true,
    countDown: false,
  },
];
